"""module containing the stop word to par the user question"""

STOPWORDS = ['rapidement', 'malheureusement', 'cherche', 'adresse', 
            'lentement', 'couramment', 'egalement', 'parfois', 'encore', 
            'tellement', 'certainement', 'probablement', 'précisément', 
            'beaucoup', 'comment', 'vas', 'souvent', 'presque', 'bientot', 
            'cependant', 'desormais', 'davantage', 'vraiment', 'habituellement', 
            'régulierement', 'tranquillement', 'calmement', 'jamais', 'partout', 
            'grandpy', 'espere', 'est', 'indiquer', 'preciser', 'merci', 'passe',
            'trouver', 'avance', 'salutations', 'salutation', 'mamie', 'trouve',
            'hier', 'était', 'serait', 'avait', 'aurait été', 'bonjour', 'bonsoir', 
            'hello', 'plait', 'salut', 'soirée', 'grandma', 'ainsi', 'ait', 'allaient',
            'après', 'as', 'assez', 'belle', 'semaine', 'a', 'abord', 'absolument', 
            'afin', 'ah', 'ai', 'aie', 'ailleurs', 'allo', 'allons', 'allô', 'alors',
            'anterieur', 'anterieure', 'anterieures', 'apres', 'attendu', 'au', 'aucun', 
            'aucune', 'aujourd', "aujourd'hui", 'aupres', 'auquel', 'aura', 'auraient', 
            'aurait', 'auxquelles', 'auxquels', 'bas', 'basee', 'bat', 'soir', 'auront', 
            'aussi', 'autre', 'autrefois', 'autrement', 'autres', 'autrui', 'aux', 'avaient', 
            'avais', 'avant', 'avec', 'avoir', 'avons', 'ayant', 'b', 'bah', 'beau', 'bien', 
            'bigre', 'boum', 'bravo', 'brrr', 'c', 'car', 'ce', 'ceci', 'cela', 'celle', 'celle-ci', 
            'certain', 'ceux-là', 'chacun', 'cinq', 'celle-là', 'celles', 'celles-ci', 'celles-là', 
            'celui', 'celui-ci', 'celui-là', 'cent', 'certaine', 'certaines', 'certains', 'certes', 
            'ces', 'cet', 'cette', 'ceux', 'ceux-ci', 'chacune', 'chaque', 'cher', 'chers', 'chez', 
            'chiche', 'chut', 'chère', 'chères', 'ci', 'cinquantaine', 'comparable', 'debout', 'dedans', 
            'desquelles', 'cinquante', 'cinquantième', 'cinquième', 'clac', 'clic', 'combien', 'comme', 
            'comparables', 'compris', 'concernant', 'contre', 'couic', 'crac', 'd', 'da', 'dans', 'de', 
            'dehors', 'deja', 'delà', 'depuis', 'dernier', 'derniere', 'derriere', 'derrière', 'des', 
            'desquels', 'dessous', 'dessus', 'deux', 'deuxième', 'deuxièmement', 'devant', 'devers', 
            'devra', 'different', 'directe', 'dix-neuf', 'dix-sept', 'durant', 'dès', 'differentes', 
            'differents', 'différent', 'différente', 'différentes', 'différents', 'dire', 'directement', 
            'dit', 'dite', 'dits', 'divers', 'diverse', 'diverses', 'dix', 'dix-huit', 'dixième', 'doit', 
            'doivent', 'donc', 'dont', 'douze', 'douzième', 'dring', 'du', 'duquel', 'désormais', 'e', 
            'effet', 'egale', 'egales', 'eh', 'elle', 'elle-même', 'elles', 'elles-mêmes', 'eu', 'euh', 
            'faisant', 'hi', 'ho', 'hé', 'hélas', 'laquelle', 'las', 'lui', 'lui-meme', 'me', 'meme', 
            'moi-meme', 'na', 'naturel', 'ni', 'nombreuses', 'moi', 'en', 'enfin', 'entre', 'envers', 
            'environ', 'es', 'et', 'etant', 'etc', 'etre', 'eux', 'eux-mêmes', 'exactement', 'excepté', 
            'extenso', 'exterieur', 'f', 'fais', 'faisaient', 'fait', 'façon', 'feront', 'fi', 'flac', 
            'floc', 'font', 'gens', 'h', 'ha', 'hein', 'hem', 'hep', 'holà', 'hop', 'hormis', 'hors', 
            'hou', 'houp', 'hue', 'hui', 'huit', 'huitième', 'hum', 'hurrah', 'i', 'il', 'ils', 'importe', 
            'j', 'je', 'jusqu', 'jusque', 'juste', 'k', 'l', 'la', 'laisser', 'g', 'le', 'lequel', 'les', 
            'lesquelles', 'lesquels', 'leur', 'leurs', 'longtemps', 'lors', 'lorsque', 'lui-même', 'là', 
            'lès', 'm', 'ma', 'maint', 'maintenant', 'mais', 'malgre', 'malgré', 'maximale', 'memes', 'mes',
             'mien', 'mienne', 'miennes', 'miens', 'mille', 'mince', 'minimale', 'n', 'moi-même', 'moindres',
              'moins', 'mon', 'moyennant', 'multiple', 'multiples', 'même', 'mêmes', 'naturelle', 'naturelles', 
              'ne', 'neanmoins', 'necessaire', 'necessairement', 'neuf', 'neuvième', 'plus', 'néanmoins', 'que', 
              'quel', 'plein', 'passé', 'oust', 'parle', 'nôtre', 'nôtres', 'ouste', 'outre', 'parlent', 'parler', 
              'pendant', 'pense', 'plouf', 'nombreux', 'non', 'nos', 'notamment', 'notre', 'nous', 'nous-mêmes', 
              'nouveau', 'nul', 'o', 'oh', 'ohé', 'ollé', 'olé', 'on', 'ont', 'onze', 'onzième', 'ore', 'ou', 'ouf', 
              'ouias', 'ouvert', 'ouverte', 'ouverts', 'o|', 'où', 'p', 'paf', 'pan', 'par', 'parce', 'parmi', 
              'parseme', 'partant', 'particulier', 'particulière', 'particulièrement', 'pas', 'permet', 'personne', 
              'peu', 'peut', 'peuvent', 'peux', 'pff', 'pfft', 'pfut', 'pif', 'pire', 'pourquoi', 'pourrais', 'pres', 
              'probable', 'q', 'qu', 'quand', 'quant', 'quatrièmement', 'plusieurs', 'plutôt', 'possessif', 
              'possessifs', 'possible', 'possibles', 'pouah', 'pour', 'pourrait', 'pouvait', 'prealable', 'precisement',
               'premier', 'première', 'premièrement', 'probante', 'procedant', 'proche', 'près', 'psitt', 'pu', 'puis',
                'puisque', 'pur', 'pure', 'quant-à-soi', 'quanta', 'quarante', 'quatorze', 'quatre', 'quatre-vingt', 
                'quatrième', 'quelconque', 'quelle', 'quelles', "quelqu'un", 'quelque', 'quelques', 'quels', 'qui', 
                'quiconque', 'quinze', 'quoi', 'rend', 'rendre', 'restant', 'sacrebleu', 'sait', 'sans', 'quoique', 
                'r', 'rare', 'rarement', 'rares', 'relative', 'relativement', 'remarquable', 'reste', 'restent', 
                'restrictif', 'retour', 'revoici', 'revoilà', 'rien', 's', 'sa', 'sapristi', 'sauf', 'se', 'sein', 
                'seize', 'selon', 'semblable', 'semblaient', 'semble', 'semblent', 'sent', 'sept', 'si', 'sien', 
                'sienne', 'son', 'sont', 'sous', 'septième', 'sera', 'sais', 'seraient', 'seront', 'ses', 'seul', 'seule',
                'seulement', 'siennes', 'siens', 'sinon', 'six', 'sixième', 'soi', 'soi-même', 'soit', 'soixante',
                'specifique', 'specifiques', 'speculatif', 'stop', 'strictement', 'subtiles', 'ô', 'suffisant',
                'suffisante', 'suffit', 'sur', 'surtout', 't', 'ta', 'tend', 'tenir', 'tente', 'tes', 'toujours', 
                'tous', 'tout', 'trop', 'très', 'v', 'va', 'vais', 'uns', 'vont', 'vos', 'votre', 'ès', 'étaient', 
                'étais', 'étant', 'été', 'être', 'suis', 'suit', 'suivant', 'suivante', 'suivantes', 'suivants', 
                'suivre', 'superpose', 'tac', 'tant', 'tardive', 'te', 'tel', 'telle', 'telles', 'tels', 'tenant', 
                'tic', 'tien', 'tienne', 'tiennes', 'tiens', 'toc', 'toi', 'toi-même', 'ton', 'troisièmement', 
                'toute', 'toutefois', 'toutes', 'treize', 'trente', 'tres', 'trois', 'troisième', 'touchant', 'tsoin',
                'tsouin', 'tu', 'té', 'u', 'un', 'une', 'unes', 'uniformement', 'unique', 'uniques', 'vers', 
                'via', 'vif', 'vifs', 'vingt', 'vivat', 'vive', 'vives', 'vlan', 'voici', 'voilà', 'vous', 
                'vous-mêmes', 'vu', 'vé', 'vôtre', 'vôtres', 'w', 'x', 'y', 'z', 'zut', 'à', 'â', 'çaaux', 
                'eus', 'serons', 'étions', 'fûtes', 'eussiez', 'soient', 'étée', 'ayants', 'fussions', 'ayez',
                'eusses', 'eûmes', 'soyez', 'serez', 'fus', 'ayante', 'étants', 'furent', 'étées', 'fût', 'aurai',
                'étantes', 'espere', 'espère', 'auriez', 'étés', 'étante', 'serais', 'eusse', 'seras', 'fusses', 'serai', 'ayons', 'sois',
                'eûtes', 'plait', 'plait', 'aurions', 'seriez', 'fussiez', 'eut', 'aient', 'aurons', 'eussent', 'eussions', 'aurais',
                'soyons', 'eurent', 'fussent', 'sommes', 'avions', 'avez', 'eues', 'ayantes', 'étiez', 'fut', 'aurez',
                'serions', 'fûmes', 'aies', 'eue', 'aviez', 'êtes', 'eût', 'fusse', 'auras']

